"""add_full_body_image_url_to_users

Revision ID: 1b2b687ec81e
Revises: add_profile_completion
Create Date: 2025-10-26 23:00:52.946728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2b687ec81e'
down_revision: Union[str, Sequence[str], None] = 'add_profile_completion'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_body_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_body_image_url')
    # ### end Alembic commands ###
